name: Mirror Repo
on: 
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        run: |
          git clone --mirror "$REPO_CLONE_URL" page.git
          cd page.git/
          git remote add github "https://$GITHUB_ACTOR:$ACTIONS_TOKEN_OVERWRITE@github.com/$GITHUB_REPOSITORY.git"
          git push --mirror github
        env: 
          ACTIONS_TOKEN_OVERWRITE: ${{ secrets.ACTIONS_TOKEN_OVERWRITE }}
          REPO_CLONE_URL: ${{ secrets.REPO_CLONE_URL }}
