name: Mirror + Deploy Repo
on: 
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'
  workflow_dispatch: 
    inputs:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      REPO_CLONE_URL: ${{ secrets.REPO_CLONE_URL }}
      ACTIONS_TOKEN_OVERWRITE: ${{ secrets.ACTIONS_TOKEN_OVERWRITE }}
    steps:
    - name: Mirror
      run: |
          git clone -b master "$REPO_CLONE_URL" master.git
          cd master.git
          git remote add github "https://$GITHUB_ACTOR:$ACTIONS_TOKEN_OVERWRITE@github.com/$GITHUB_REPOSITORY.git"
          git push github master
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Deploy
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACTIONS_TOKEN_OVERWRITE }}
        deploy-branch: gh-pages
